version: '3.8'

services:
  # xRegistry Viewer - Unified application with integrated proxy
  xregistry-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xregistry-viewer
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      # Mount config for runtime configuration updates
      - ./public/config.json:/app/dist/xregistry-viewer/browser/config.json:ro
    networks:
      - xregistry-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  xregistry-network:
    driver: bridge
